Increment23 implementation
fuzzy-toozy/metrics-service pull request #27
Opened 2024-05-12 19:38 UTC by fuzzy-toozy

2024-05-13 19:03 UTC, tmvrus requested changes

2024-05-13 19:03 UTC, tmvrus commented on internal/server/handlers/encryption.go
> +		}
тут есть одна и та же ошибка. два раза

2024-05-13 19:03 UTC, tmvrus commented on internal/agent/agent.go
> +		signal.Notify(c, os.Interrupt, syscall.SIGTERM, syscall.SIGQUIT)
довольно четко написано какие сигналы нужно обрабатывать
<img width="714" alt="image" src="https://github.com/fuzzy-toozy/metrics-service/assets/554425/d1927eb1-0712-4604-a38a-48a8e6c26497">

2024-05-13 20:30 UTC, fuzzy-toozy commented on internal/agent/agent.go
> +		signal.Notify(c, os.Interrupt, syscall.SIGTERM, syscall.SIGQUIT)
Именно они тут и перехватываются, разве нет?

2024-05-13 20:37 UTC, fuzzy-toozy commented on internal/server/handlers/encryption.go
> +		}
fixed

2024-05-14 11:42 UTC, tmvrus commented on internal/agent/agent.go
> +		signal.Notify(c, os.Interrupt, syscall.SIGTERM, syscall.SIGQUIT)
в списке предложенных есть разве os.Interrupt ?

2024-05-14 12:24 UTC, fuzzy-toozy commented on internal/agent/agent.go
> +		signal.Notify(c, os.Interrupt, syscall.SIGTERM, syscall.SIGQUIT)
Я не понимаю как ваше замечание помогает моему образовательному процессу. Программа перехватывает sigint и это и требовалось в задании. Чего же ради вы уперлись?

2024-05-14 14:28 UTC, tmvrus commented on internal/agent/agent.go
> +		signal.Notify(c, os.Interrupt, syscall.SIGTERM, syscall.SIGQUIT)
С таким заявлениями я предлагаю тебе обратится к куратору.

2024-05-20 06:51 UTC, bambruysk approved these changes
Очень хорошо

2024-05-20 06:51 UTC, bambruysk commented on internal/config/common.go
> +func (o *DurationOption) UnmarshalJSON(data []byte) error {
Хорошее расширение 👍

2024-05-20 10:46 UTC, merged